### ISSUE TITLE
consider updating figwheel-bridge to latest version

### ISSUE THREAD

**Issue by carocad** [tiensonqin/exponent-cljs-template#43]
The maintainer of `figwheel` recently did a refactor of the bridge used for react native to enable new capabilities of figwheel.

It would be nice if you could update the file accordingly.

- link to latest version: https://github.com/drapanjanas/re-natal/blob/master/resources/figwheel-bridge.js
- history: https://github.com/drapanjanas/re-natal/commits/master/resources/figwheel-bridge.js

**Comment by seantempesta** [comment]
Whew.  Took a few hours, but I got everything working.  There are only minimal changes now between re-natal's figwheel-bridge and the expo template:
```
sean@sean-mac ~/s/expo-cljs-template> diff resources/leiningen/new/expo/js/figwheel-bridge.js ~/src/re-natal-test/figwheel-bridge.js 
13c13
<     serverPort: 19001
---
>     serverPort: 8081
193c193
<     var mainJs = `/env/expo/main.js`;
---
>     var mainJs = `/env/${platform}/main.js`;
215c215
<                 googreq(`figwheel.connect.build_main`);
---
>                 googreq(`env.${platform}.main`);
```
This required shifting some files around in the `env` folder and adjusting the project files to build to `target/expo` instead of `target`.  If you want to pickup the new changes I recommend creating a new project and running a diff to see what files changes and then matching those changes.

**Comment by carocad** [comment]
@seantempesta thanks a lot for the fast update !!
